fastlane_version "2.157"
default_platform :ios

platform :ios do
  desc "Build projects and executes unit tests"
  lane :unit_test do |options|
    scan(
      clean: options.fetch(:clean, true),
      skip_package_dependencies_resolution: options.fetch(:skip_package_dependencies_resolution, false)
      # Puedes añadir más opciones si las necesitas, por ejemplo:
      # scheme: "TuScheme",
      # project: "TuProyecto.xcodeproj",
      # devices: ["iPhone 16"],
      # derived_data_path: "build/DerivedData",
      # result_bundle: true
    )
  end
end
